# Generated by Django 5.2.3 on 2025-07-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universepro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Universepro', max_length=100, verbose_name='site name')),
                ('site_logo', models.ImageField(blank=True, upload_to='site/', verbose_name='site logo')),
                ('favicon', models.ImageField(blank=True, upload_to='site/', verbose_name='favicon')),
                ('email', models.EmailField(default='contact@universepro.com', max_length=254, verbose_name='email')),
                ('phone', models.CharField(default='+22893020525', max_length=20, verbose_name='phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('facebook_url', models.URLField(blank=True, verbose_name='facebook url')),
                ('twitter_url', models.URLField(blank=True, verbose_name='twitter url')),
                ('instagram_url', models.URLField(blank=True, verbose_name='instagram url')),
                ('whatsapp_phone', models.CharField(default='+22893020525', max_length=20, verbose_name='whatsapp phone')),
                ('whatsapp_message', models.TextField(default="Bonjour, j'ai une question sur votre boutique en ligne.", verbose_name='whatsapp default message')),
                ('currency', models.CharField(default='FCFA', max_length=10, verbose_name='currency')),
                ('currency_symbol', models.CharField(default='F', max_length=3, verbose_name='currency symbol')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=100000.0, max_digits=10, verbose_name='free shipping threshold')),
                ('default_shipping_cost', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name='default shipping cost')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='maintenance message')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta description')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='meta keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site setting',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
