# Generated by Django 5.2.3 on 2025-08-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universepro', '0002_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingproduct',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
